### ISSUE TITLE
Running safe autocorrect?

### ISSUE THREAD

**Issue by vfonic** [Ragnarson/ragnarson-stylecheck#19]
Cześć!

I just discovered your gem and am trying to configure it to work on my projects. Thanks for building it! It's really useful!

I inherited a rails app from a new client and, after running `rubocop --auto-correct`, the app broke. I didn't know this was possible, and then I discovered the "Safe autocorrect": `rubocop --safe-auto-correct`
https://rubocop.readthedocs.io/en/latest/auto_correct/
I think this would be better/safer option.
It would be great to have such an option here: https://github.com/Ragnarson/ragnarson-stylecheck/blob/master/lib/ragnarson/tasks/rubocop.rake
Maybe even make it a default `rake style` task?

Thanks!
Viktor

**Comment by Nytorian** [comment]
Why not use Rubocop instead wrapped up in a simple rake task?
This gem is nothing but a boilerplate anyway.

**Comment by enigmatt-pl** [comment]
Why not use Rubocop wrapped up in a simple rake task?
This gem is nothing but a boilerplate anyway.

**Comment by vfonic** [comment]
Because I can't share a rake file across multiple projects and team so easily.

**Comment by enigmatt-pl** [comment]
From what you wrote above, I assume you don't even use this gem... (`rubocop --auto-correct` :eyes:)

**All you need is:**
- install rubocop (this gem's dependency ~> 0.64) -> https://tinyurl.com/y36trbxp
- paste the content of https://tinyurl.com/y33y5o8p (current config file) into `config/.rubocop.yml` (in your rails project)

And enjoy `rubocop --safe-auto-correct` and Rubocop in general without a limiting/poorly maintained boilerplate.

Kind Regards

**Comment by vfonic** [comment]
I'm using a fork of this gem, as I can specify cli arguments and have the team use the same cli arguments and also have a special rake task for CI.

And also use one/update one config across all projects.

Thanks for the advices. My setup works for me. 

I'll close this issue, this discussion is not going anywhere.

**Comment by enigmatt-pl** [comment]
Well, you've missed the fact that you completely refactored the gem :joy: and that you're just suggesting a new 'feature' request here. The issue/feature request should be left open in this case imo. I just intended to help you get rid of unnecessary weight since you were not even using this gem looking at the comments.

Regards
